# Generated by Django 4.1.5 on 2023-02-22 09:46

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category_id",
            field=models.ForeignKey(
                default=builtins.id,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.category",
            ),
        ),
    ]
