# Generated by Django 4.1.5 on 2023-02-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_book_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="about",
        ),
        migrations.AlterField(
            model_name="book",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.category"
            ),
        ),
    ]
