# Generated by Django 4.1.5 on 2023-02-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
