# Generated by Django 4.1.5 on 2023-02-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_book_category_alter_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(
                default=1, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
