# Generated by Django 4.1.5 on 2023-02-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
